forum/forum/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from main_app.admin import admin_site
from forum import settings


urlpatterns = [
    path('admin/', admin_site.urls),
    path('', include(('main_app.urls', 'main'), namespace='main')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'main.views.handler404'
handler500 = 'main.views.handler500'

forum/main_app/urls.py
from django.urls import path
from django.conf.urls import include
from main_app import views


urlpatterns = [
        path('index/<page_number>', views.IndexView.as_view(), name='index'),
        path('', views.redirect_to_index),
        path('thread/<int:pk>', views.ThreadView.as_view(), name='thread'),
        path('create_thread', views.CreateThreadView.as_view(), name='create_thread'),
        path('profile', views.ProfileView.as_view(), name='profile'),
        path('register', views.ForumUserFormView.as_view(), name='register'),
        path('delete_post/', views.delete_post, name='delete_post'),
        path('delete_thread/<int:pk>', views.delete_thread, name='delete_thread'),
        path('like_and_dislike/', views.like_and_dislike, name='like_and_dislike'),
        path('about/<int:pk>', views.AboutForumUserView.as_view(), name='about')

]

forum/main_app/models.py
from django.db import models
import random, os
from forum import settings
from django.contrib.auth.models import User


class ForumUser(User):
    GENDER_CHOICES = (
        ('', 'Выбор пола'),
        ('M', 'Мужчина'),
        ('F', 'Женщина'),)
    city = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    avatar = models.ImageField(upload_to="avatars")

    def delete(self, *args, **kwargs):
        if os.path.isfile(self.avatar.path):
            os.remove(self.avatar.path)
        super(ForumUser, self).delete(*args,**kwargs)

    def random_avatar(self):
        list_images = os.listdir(path=settings.RANDOM_AVATARS)
        if self.gender == 'M':
            male_avatars = list(filter(lambda gender: gender.startswith('boy'), list_images))
            return settings.RANDOM_AVATARS_URL + random.choice(male_avatars)
        else:
            female_avatars = list(filter(lambda gender: gender.startswith('girl'), list_images))
            return settings.RANDOM_AVATARS_URL + random.choice(female_avatars)

    @property
    def reputation(self):
        likes_thread = Thread.objects.filter(user=self.id)
        likes_post = Post.objects.filter(user=self.id)
        total_likes = 0
        total_dislikes = 0
        for item in list(likes_thread) + list(likes_post):
            total_likes += item.likes.count()
            total_dislikes += item.dislikes.count()
        return total_likes - total_dislikes

    @property
    def thread_count(self):
        return Thread.objects.filter(user=self.id).count()

    @property
    def post_count(self):
        return Post.objects.filter(user=self.id).count()


class Thread(models.Model):
    title = models.CharField(max_length=24)
    description = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(ForumUser, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images", blank=True, null=True)
    likes = models.ManyToManyField(ForumUser, related_name="thread_likes", blank=True)
    dislikes = models.ManyToManyField(ForumUser, related_name="thread_dislikes", blank=True)

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        if self.image:
            if os.path.isfile(self.image.path):
                os.remove(self.image.path)
        super(Thread, self).delete(*args,**kwargs)

    @property
    def likes_count(self):
        return self.likes.count()

    @property
    def dislikes_count(self):
        return self.dislikes.count()

    @property
    def post_count(self):
        return Post.objects.filter(thread=self.id).count()


class Post(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    title = models.CharField(max_length=24)
    description = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(ForumUser, on_delete=models.CASCADE)
    likes = models.ManyToManyField(ForumUser, related_name="post_likes", blank=True)
    dislikes = models.ManyToManyField(ForumUser, related_name="post_dislikes", blank=True)

    def __str__(self):
        return self.title

    @property
    def likes_count(self):
        return self.likes.count()

    @property
    def dislikes_count(self):
        return self.dislikes.count()

forum/main_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import ForumUser, Thread, Post


class ForumUserCreationForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = ForumUser
        fields = ("username", "gender", "password1", "password2")

        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Логин'
                    }
                ),
            'gender': forms.Select(
                attrs={
                    'class': 'form-control',
                    }
                )
            }


class ThreadCreateForm(forms.ModelForm):
    class Meta:
        model = Thread
        fields = ("title", "description", "image")

        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Название темы'
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Текст темы'
                }
            ),
        }


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "description")

        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'reply-post form-control',
                    'placeholder': 'Заголовок ответа'
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Текст ответа'
                }
            ),
        }


class ForumUserUpdateForm(forms.Form):
    email = forms.EmailField(required=False, label='Электронная почта')
    first_name = forms.CharField(required=False, label='Имя')
    last_name = forms.CharField(required=False, label='Фамилия')
    city = forms.CharField(required=False, label='Город')
    avatar = forms.ImageField(required=False, label='Аватар')

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(ForumUserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget = forms.EmailInput(attrs={'class': 'form-control', 'value': self.request.user.email})
        self.fields['first_name'].widget = forms.TextInput(attrs={'class': 'form-control', 'value': self.request.user.first_name})
        self.fields['last_name'].widget = forms.TextInput(attrs={'class': 'form-control', 'value': self.request.user.last_name})
        self.fields['city'].widget = forms.TextInput(attrs={'class': 'form-control', 'value': ForumUser.objects.get(username=self.request.user).city})
        self.fields['avatar'].widget = forms.FileInput(attrs={'id': 'file-input' })

forum/main_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.http import JsonResponse
from django.urls import reverse
from django.views.generic.edit import FormView
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import ForumUser, Thread, Post
from .forms import ForumUserCreationForm, ThreadCreateForm, CreatePostForm, ForumUserUpdateForm
from .decorators import check_post_user_id


class ForumUserFormView(FormView):

    form_class = ForumUserCreationForm
    success_url = "/accounts/login"
    template_name = "registration.html"

    def form_valid(self, form):
        user = form.save(commit=False)
        user.avatar = user.random_avatar()
        user.save()
        return super(ForumUserFormView, self).form_valid(form)


class IndexView(View):

    template_name = 'index.html'

    def get(self, request, page_number):
        query = Thread.objects.all().order_by('-date')
        if query.count() != 0:
            query_page = Paginator(query, 9)
            try:
                pages = query_page.page(page_number)
            except PageNotAnInteger:
                pages = query_page.page(1)
            except EmptyPage:
                pages = query_page.page(query_page.num_pages)
            args = {"query": pages}
        else:
            args = {"none": "Нет записей"}
        return render(request, self.template_name, args)


class ThreadView(View):

    template_name = 'thread.html'

    def get(self, request, pk):
        form = CreatePostForm()
        thread = Thread.objects.get(id=pk)
        posts = Post.objects.filter(thread=thread)
        args = {"thread": thread, "posts": posts, "form": form}
        return render(request, self.template_name, args)

    @method_decorator(login_required)
    def post(self, request, pk):
        form = CreatePostForm(request.POST)
        thread = Thread.objects.get(id=pk)
        posts = Post.objects.filter(thread=thread)
        args = {"thread": thread, "posts": posts, "form": form}
        if form.is_valid():
            post = form.save(commit=False)
            post.user = ForumUser.objects.get(username=request.user)
            post.thread = thread
            post.save()
            return redirect(reverse('main:thread', kwargs={'pk': thread.id}))
        return render(request, self.template_name, args)


class CreateThreadView(View):

    template_name = "create_thread.html"

    @method_decorator(login_required)
    def get(self, request):
        form = ThreadCreateForm()
        args = {"form": form}
        return render(request, self.template_name, args)

    @method_decorator(login_required)
    def post(self, request):
        form = ThreadCreateForm(request.POST, request.FILES)
        args = {"form": form}
        if form.is_valid():
            thread = form.save(commit=False)
            thread.user = ForumUser.objects.get(username=request.user)
            thread.image = request.FILES.get('image')
            thread.save()
            return redirect(reverse('main:thread', kwargs={'pk': thread.id}))
        return render(request, self.template_name, args)


class ProfileView(View):

    template_name = 'profile.html'

    @method_decorator(login_required)
    def get(self, request):
        form = ForumUserUpdateForm(request=request)
        profile = ForumUser.objects.get(username=request.user)
        args = {"profile": profile, "form": form}
        return render(request, self.template_name, args)

    @method_decorator(login_required)
    def post(self, request):
        form = ForumUserUpdateForm(request.POST, request.FILES, request=request)
        profile = ForumUser.objects.get(username=request.user)
        args = {"profile": profile, "form": form}
        if form.is_valid():
            profile.email = form.cleaned_data.get('email')
            profile.first_name = form.cleaned_data.get('first_name')
            profile.last_name = form.cleaned_data.get('last_name')
            profile.city = form.cleaned_data.get('city')
            if form.cleaned_data.get('avatar') == None:
                pass
            else:
                profile.avatar = form.cleaned_data.get('avatar')
            profile.save()
            return redirect('main:profile')
        return render(request, self.template_name, args)


@login_required
@check_post_user_id
@require_POST
def delete_post(request):
    id = request.POST['post_id']
    if request.method == 'POST':
        post = get_object_or_404(Post, id=id)
        post.delete()
        return redirect(reverse('main:thread', kwargs={'pk': post.thread.id}))


@login_required
def delete_thread(request, pk):
    try:
        thread = Thread.objects.get(user=request.user, id=pk).delete()
    except Exception as e:
        pass
    return redirect(reverse('main:index', kwargs={'page_number': 1}))



@login_required
@require_POST
def like_and_dislike(request):
    if request.method == 'POST':
        user = ForumUser.objects.get(username=request.user)
        pk = request.POST.get('pk')
        if request.POST.get('model') == 'thread':
            model = get_object_or_404(Thread, id=pk)
        else:
            model = get_object_or_404(Post, id=pk)

        if request.POST.get('type') == 'like':
            if model.likes.filter(id=user.id).exists():
                model.likes.remove(user)
            else:
                model.likes.add(user)
            response = {'likes_count': model.likes_count}
        else:
            if model.dislikes.filter(id=user.id).exists():
                model.dislikes.remove(user)
            else:
                model.dislikes.add(user)
            response = {'dislikes_count': model.dislikes_count}
    return JsonResponse(response)


class AboutForumUserView(View):

    template_name = 'about.html'

    def get(self, request, pk):
        forumuser = ForumUser.objects.get(id=pk)
        args = {"user": forumuser }
        return render(request, self.template_name, args)


def redirect_to_index(request):
    return redirect('main:index', page_number=1)


def handler404(request):
    response = render_to_response('404.html')
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('500.html')
    response.status_code = 500
    return response

forum/main_app/templates/about.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles%}
<div class="container">
  <div class="card pb-3 pt-3 pl-3 pr-3">
    <div class="card-header text-center">
      <h3>{{ user.username }}</h3>
    </div>
    <div class="row">
      <div class="col-md-3 pb-3 pt-3 pl-3 pr-3">
        <img src="{{ user.avatar.url }}" style="box-shadow: 3px 3px;"/>
      </div>
      <div class="col-md-6 text-center">
        <p>Имя: {{ user.first_name }}</p>
        <p>Фамилия: {{ user.last_name }}</p>
        {% if user.gender == 'M' %}
          <p>Пол: Мужчина</p>
        {% else %}
          <p>Пол: Женщина</p>
        {% endif %}
        <p>Город: {{ user.city }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Репутация: {{ user.reputation }}</p>
        <p>Количество тем: {{ user.thread_count }}</p>
        <p>Количество постов: {{ user.post_count }}</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

forum/main_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Forum</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/mdb.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" type="text/css">
  <link rel="shortcut icon" href="{%  static 'images/favicon.ico' %}">
  <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
  <header>
    <nav class="navbar navbar-light navbar-expand-sm fixed-top bg-info">
		  <a><img src="{% static 'images/logo.png' %}" width="50" height="50"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar1" aria-controls="navbar1" aria-expanded="false" aria-label="Toggle navigation">
    	   <span class="navbar-toggler-icon"></span>
  	   </button>
		  <div class="collapse navbar-collapse" id="navbar1">
			   <ul class="navbar-nav navbar-right">
           <li class="nav-item active mr-2 ml-2 mb-1 mt-1">
             <a class="nav-link text-center" href="{% url 'main:index' page_number=1 %}">На главную</a>
           </li>
           {% if user.is_authenticated %}
           <li class="nav-item active mr-2 ml-2 mb-1 mt-1">
             <a class="nav-link text-center" href="{% url 'main:profile' %}">Профиль</a>
           </li>
            <li class="nav-item active mr-2 ml-2 mb-1 mt-1">
              <a class="nav-link text-center" href="{% url 'main:create_thread' %}">Создать тему</a>
             </li>
             <li class="nav-item active mr-2 ml-2 mb-1 mt-1">
               <a class="nav-link text-center" href="{% url 'logout' %}?next={{ request.path | urlencode }}">Выйти</a>
              </li>
            {% else %}
            <li class="nav-item active mr-2 ml-2 mb-1 mt-1">
              <a class="nav-link text-center" href="{% url 'login' %}">Войти</a>
             </li>
             <li class="nav-item active mr-2 ml-2 mb-1 mt-1">
               <a class="nav-link text-center" href="{% url 'main:register' %}">Зарегистрироваться</a>
            </li>
            {% endif %}
		   	</ul>
		  </div>
	  </nav>
  </header>
  <div>
    <div class="content-block pb-2 pt-2 pl-2 pr-2">
      {% block content %}
      {% endblock %}
    </div>
    <footer class="footer">
    <div class="page-footer font-small grey darken-2 mt-3">
      <div class="footer-copyright text-center py-3">
        <a class="text-light">© 2018 Copyright:</a>
        <a class="text-light">Дубровин Иван</a>
      </div>
    </div>
  </footer>
  </div>
  <script>
  $('.like_post').click(function(){
      $.ajax({
               type: "POST",
               url: "{% url 'main:like_and_dislike' %}",
               data: {'pk': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}', 'model': 'post', 'type': 'like'},
               dataType: "json",
               success: function(response) {
                      $('.like_post').val(response.likes_count);
                },
                error: function(rs, e) {
                       console.log(rs.responseText);
                }
          });
    });
    $('.dislike_post').click(function(){
        $.ajax({
                 type: "POST",
                 url: "{% url 'main:like_and_dislike' %}",
                 data: {'pk': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}', 'model': 'post', 'type': 'dislike'},
                 dataType: "json",
                 success: function(response) {
                        $('.dislike_post').val(response.dislikes_count);
                  },
                  error: function(rs, e) {
                         console.log(rs.responseText);
                  }
            });
      });
      $('.like_thread').click(function(){
          $.ajax({
                   type: "POST",
                   url: "{% url 'main:like_and_dislike' %}",
                   data: {'pk': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}', 'model': 'thread', 'type': 'like'},
                   dataType: "json",
                   success: function(response) {
                          $('.like_thread').val(response.likes_count);
                    },
                    error: function(rs, e) {
                           console.log(rs.responseText);
                    }
              });
        });
        $('.dislike_thread').click(function(){
            $.ajax({
                     type: "POST",
                     url: "{% url 'main:like_and_dislike' %}",
                     data: {'pk': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}', 'model': 'thread', 'type': 'dislike'},
                     dataType: "json",
                     success: function(response) {
                            $('.dislike_thread').val(response.dislikes_count);
                      },
                      error: function(rs, e) {
                             console.log(rs.responseText);
                      }
                });
          });
  </script>
</body>
</html>

forum/main_app/templates/create_thread.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles%}
<div class="row">
  <div class="col-md-4">
  </div>
  <div class="col-md-4">
    <div class="card pb-3 pt-3 pl-3 pr-3">
      <h3 class="text-center">Создать тему</h3>
      <div class="card-body text-center">
      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {% for field in form %}
          <h3>{{ field }}</h3>
          {% for error in field.errors %}
            <p style="color: red">{{ error|escape }}</p>
          {% endfor %}
        {% endfor %}
        <button class="btn btn-primary" type="submit">Создать тему</button>
      </form>
      </div>
    </div>
  </div>
  <div class="col-md-4">
  </div>
</div>
{% endblock %}

forum/main_app/templates/index.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles%}
<div class="jumbotron text-center">
    <img src="{% static 'images/Chat.png' %}" width="150" height="150"/>
    <h1>Форум для общения на разные темы</h1>
</div>
    <div class="container-fluid">
      <div class="row">
        {% for thread in query %}
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-header text-center">
              <h2>{{ thread.title }}</h2>
            </div>
            <div class="card-body">
              <p class="card-text">{% if thread.image %}<img src="{{ thread.image.url }}"/>{% endif %}{{ thread.description }}</p>
              <div class="card-footer">
                <p class="text-right">Автор: {{ thread.user.username }}, {{ thread.date }}, Количество постов: {{ thread.post_count }}</p>
              </div>
              <form class="text-right" action="{% url 'main:thread' pk=thread.id %}">
                <input class="btn btn-primary" type="submit" value="Открыть"/>
              </form>
            </div>
          </div>
        </div>
      {% endfor %}
      </div>
    </div>
    <div class="pagination justify-content-center mb-4">
      <ul class="pagination bg-light pagination-circle pg-blue mb-0">
          {% if query.has_previous %}
            <li class="page-item"><a class="page-link" href="{{ query.previous_page_number }}">Назад</a></li>
          {% else %}
            <li class="page-item disabled"><a class="page-link" href="">Назад</a></li>
          {% endif %}
          {% if query.number|add:'-4' > 1 %}
            <li href="{{ query.number|add:'-5' }}">&hellip;</li>
          {% endif %}
          {% for page in query.paginator.page_range %}
            {% if query.number == page %}
              <li class="page-item active"><a class="page-link" href="{{ page }}">{{ page }}</a></li>
            {% elif page > query.number|add:'-3' and page < query.number|add:'3' %}
              <li class="page-item"><a class="page-link" href="{{ page }}">{{ page }}</a></li>
            {% endif %}
          {% endfor %}
          {% if query.paginator.num_pages > query.number|add:'4' %}
            <li href="{{ query.number|add:'5' }}">&hellip;</li>
          {% endif %}
          {% if query.has_next %}
              <li class="page-item"><a class="page-link" href="{{ query.next_page_number }}">Вперед</a></li>
          {% else %}
            <li class="page-item disabled"><a class="page-link" href="">Вперед</a></li>
          {% endif %}
      </ul>
    </div>
  </div>
{% endblock %}

forum/main_app/templates/thread.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles%}
<div class="row justify-content-center mb-3">
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
    <div class="card">
      <div class="row">
        <div class="col-md-2 pb-3 pt-3 pl-3 text-center">
          <p><img src="{{ thread.user.avatar.url }}" width="80" height="80"></p>
          <p>Автор: <a href="{% url 'main:about' pk=thread.user.id %}">{{ thread.user.username }}</a></p>
          <p>{{ thread.date }}</p>
          <p>Репутация: {{ thread.user.reputation }}</p>
        </div>
        <div class="col-md-10">
          <div class="card-text pb-2 pt-2 pl-2 pr-2">
            <h4 class="text-center">{{ thread.title }}</h4>
            <p>{% if thread.image %}<img class="thread-image" src="{{ thread.image.url }}">{% endif %}{{ thread.description }}</p>
          </div>
        </div>
      </div>
      <div class="card-footer text-muted">
        {% if user.is_authenticated %}
        <div class="text-right">
          <i class="fa fa-thumbs-up fa-2x"></i><input id="like-button" class="btn btn-primary like_thread" type="button" name="{{ thread.id }}" value="{{ thread.likes_count }}" />
          <i class="fa fa-thumbs-down fa-2x"></i><input id="like-button" class="btn btn-primary dislike_thread" type="button" name="{{ thread.id }}" value="{{ thread.dislikes_count }}" />
        </div>
        {% if user.id == thread.user.id %}
          <button onclick="DeleteThread()" class="btn btn-primary">Удалить</button>
          <script>
            function DeleteThread() {
              var r = confirm("Вы действительно хотите удалить эту тему?");
              if (r == true) {
                    $(location).attr('href', '{% url 'main:delete_thread' pk=thread.id %}');
                   }
              else {}
              };
          </script>
        {% endif %}
        {% else %}
        <div class="text-right">
          <i class="fa fa-thumbs-up fa-2x">{{ thread.likes_count }}</i>
          <i class="fa fa-thumbs-down fa-2x">{{ thread.dislikes_count }}</i>
        </div>
        {% endif %}
        </div>
      </div>
    </div>
    <div class="col-md-2">
    </div>
  </div>
  {% for post in posts %}
  <div class="row justify-content-center mb-3">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="row">
          <div class="col-md-3 pb-3 pt-3 pl-3 pr-3 text-center">
            <p><img src="{{ post.user.avatar.url }}" width="80" height="80"></p>
            <p>Автор: <a href="{% url 'main:about' pk=post.user.id %}">{{ post.user.username }}</a></p>
            <p>{{ post.date }}</p>
            <p>Репутация: {{ post.user.reputation }}</p>
          </div>
          <div class="col-md-9">
            <div class="card-text pb-2 pt-2 pl-2 pr-2">
              <h4 class="text-center">{{ post.title }}</h4>
              <p>{{ post.description }}</p>
            </div>
          </div>
        </div>
        <div class="card-footer text-muted">
          <div class="text-right">
          {% if user.is_authenticated %}
            <i class="text-left pr-3">Номер поста: {{ post.id }}</i>
            <i class="fa fa-thumbs-up fa-2x"></i><input id="like-button" class="btn btn-primary like_post" type="button" name="{{ post.id }}" value="{{ post.likes_count }}" />
            <i class="fa fa-thumbs-down fa-2x"></i><input id="like-button" class="btn btn-primary dislike_post" type="button" name="{{ post.id }}" value="{{ post.dislikes_count }}" />
            <button onclick="ReplyPost{{ post.id }}()" class="btn btn-primary">Ответить на пост</button>
            <script type="text/javascript">
              function ReplyPost{{ post.id }}() {
                  $('.reply-post').val('Ответ на пост' + ' ' + {{ post.id }});
                };
            </script>
          {% else %}
              <i class="text-left pr-3">Номер поста: {{ post.id }}</i>
              <i class="fa fa-thumbs-up fa-2x">{{ post.likes_count }}</i>
              <i class="fa fa-thumbs-down fa-2x">{{ post.dislikes_count }}</i>
          {% endif %}
          </div>
          {% if user.id == post.user.id %}
             <form action = "{% url 'main:delete_post' %}" method = "POST">
               {% csrf_token %}
               <input type="hidden" name="post_id" value="{{ post.id }}"/>
               <input class="btn btn-primary" type="submit" value="удалить"/>
             </form>
          {% endif %}
         </div>
        </div>
      </div>
      <div class="col-md-3">
      </div>
    </div>
    {% endfor %}
  {% if user.is_authenticated %}
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
      <div class="card-body text-center">
        <form enctype="multipart/form-data" method="post">
          {% csrf_token %}
          {% for field in form %}
            <h3>{{ field }}</h3>
            {% for error in field.errors %}
              <p style="color: red">{{ error|escape }}</p>
            {% endfor %}
          {% endfor %}
          <button class="btn btn-primary" type="submit">Ответить</button>
        </form>
      </div>
    </div>
    <div class="col-md-4">
    </div>
  </div>
{% endif %}
{% endblock %}